// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using library.Data;

#nullable disable

namespace library.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("library.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<bool>("Signed")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "M. Castillo",
                            Description = "Short chapters, practical insights, and zero fluff—made for busy readers.",
                            ImagePath = "https://picsum.photos/seed/library_book_1/600/900",
                            Rating = 4.2999999999999998,
                            Signed = true,
                            Title = "Pages of Time #1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "R. Bennett",
                            Description = "A field note from the front desk: what to keep, what to search, and when.",
                            ImagePath = "https://picsum.photos/seed/library_book_2/600/900",
                            Rating = 3.3999999999999999,
                            Signed = true,
                            Title = "Ink & Ideas #2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "L. Nakamura",
                            Description = "Tiny patterns that scale from a single page to a whole system.",
                            ImagePath = "https://picsum.photos/seed/library_book_3/600/900",
                            Rating = 3.8999999999999999,
                            Signed = false,
                            Title = "Beyond The Stacks #3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "H. Ibrahim",
                            Description = "Calm explanations with examples you can try the same day.",
                            ImagePath = "https://picsum.photos/seed/library_book_4/600/900",
                            Rating = 3.3999999999999999,
                            Signed = false,
                            Title = "Patterns of Code #4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "C. Martin",
                            Description = "A concise, human-friendly guide that turns complex ideas into daily tools.",
                            ImagePath = "https://picsum.photos/seed/library_book_5/600/900",
                            Rating = 4.0,
                            Signed = true,
                            Title = "Sands of Memory #5"
                        },
                        new
                        {
                            Id = 6,
                            Author = "S. Patel",
                            Description = "Short chapters, practical insights, and zero fluff—made for busy readers.",
                            ImagePath = "https://picsum.photos/seed/library_book_6/600/900",
                            Rating = 3.2999999999999998,
                            Signed = false,
                            Title = "Hidden Chapters #6"
                        },
                        new
                        {
                            Id = 7,
                            Author = "N. Alvarez",
                            Description = "A field note from the front desk: what to keep, what to search, and when.",
                            ImagePath = "https://picsum.photos/seed/library_book_7/600/900",
                            Rating = 4.4000000000000004,
                            Signed = true,
                            Title = "The Archivist #7"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Y. Chen",
                            Description = "Tiny patterns that scale from a single page to a whole system.",
                            ImagePath = "https://picsum.photos/seed/library_book_8/600/900",
                            Rating = 3.8999999999999999,
                            Signed = true,
                            Title = "Refactor Your Mind #8"
                        },
                        new
                        {
                            Id = 9,
                            Author = "D. Howard",
                            Description = "Calm explanations with examples you can try the same day.",
                            ImagePath = "https://picsum.photos/seed/library_book_9/600/900",
                            Rating = 3.2000000000000002,
                            Signed = false,
                            Title = "Designing Harmony #9"
                        },
                        new
                        {
                            Id = 10,
                            Author = "A. Reynolds",
                            Description = "A concise, human-friendly guide that turns complex ideas into daily tools.",
                            ImagePath = "https://picsum.photos/seed/library_book_10/600/900",
                            Rating = 4.0,
                            Signed = false,
                            Title = "The Silent Library #10"
                        },
                        new
                        {
                            Id = 11,
                            Author = "M. Castillo",
                            Description = "Short chapters, practical insights, and zero fluff—made for busy readers.",
                            ImagePath = "https://picsum.photos/seed/library_book_11/600/900",
                            Rating = 4.7999999999999998,
                            Signed = true,
                            Title = "Pages of Time #11"
                        },
                        new
                        {
                            Id = 12,
                            Author = "R. Bennett",
                            Description = "A field note from the front desk: what to keep, what to search, and when.",
                            ImagePath = "https://picsum.photos/seed/library_book_12/600/900",
                            Rating = 3.5,
                            Signed = false,
                            Title = "Ink & Ideas #12"
                        },
                        new
                        {
                            Id = 13,
                            Author = "L. Nakamura",
                            Description = "Tiny patterns that scale from a single page to a whole system.",
                            ImagePath = "https://picsum.photos/seed/library_book_13/600/900",
                            Rating = 3.2999999999999998,
                            Signed = true,
                            Title = "Beyond The Stacks #13"
                        },
                        new
                        {
                            Id = 14,
                            Author = "H. Ibrahim",
                            Description = "Calm explanations with examples you can try the same day.",
                            ImagePath = "https://picsum.photos/seed/library_book_14/600/900",
                            Rating = 4.9000000000000004,
                            Signed = false,
                            Title = "Patterns of Code #14"
                        },
                        new
                        {
                            Id = 15,
                            Author = "C. Martin",
                            Description = "A concise, human-friendly guide that turns complex ideas into daily tools.",
                            ImagePath = "https://picsum.photos/seed/library_book_15/600/900",
                            Rating = 4.7999999999999998,
                            Signed = true,
                            Title = "Sands of Memory #15"
                        },
                        new
                        {
                            Id = 16,
                            Author = "S. Patel",
                            Description = "Short chapters, practical insights, and zero fluff—made for busy readers.",
                            ImagePath = "https://picsum.photos/seed/library_book_16/600/900",
                            Rating = 4.5,
                            Signed = true,
                            Title = "Hidden Chapters #16"
                        },
                        new
                        {
                            Id = 17,
                            Author = "N. Alvarez",
                            Description = "A field note from the front desk: what to keep, what to search, and when.",
                            ImagePath = "https://picsum.photos/seed/library_book_17/600/900",
                            Rating = 4.2000000000000002,
                            Signed = true,
                            Title = "The Archivist #17"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Y. Chen",
                            Description = "Tiny patterns that scale from a single page to a whole system.",
                            ImagePath = "https://picsum.photos/seed/library_book_18/600/900",
                            Rating = 4.5,
                            Signed = true,
                            Title = "Refactor Your Mind #18"
                        },
                        new
                        {
                            Id = 19,
                            Author = "D. Howard",
                            Description = "Calm explanations with examples you can try the same day.",
                            ImagePath = "https://picsum.photos/seed/library_book_19/600/900",
                            Rating = 3.8999999999999999,
                            Signed = false,
                            Title = "Designing Harmony #19"
                        },
                        new
                        {
                            Id = 20,
                            Author = "A. Reynolds",
                            Description = "A concise, human-friendly guide that turns complex ideas into daily tools.",
                            ImagePath = "https://picsum.photos/seed/library_book_20/600/900",
                            Rating = 3.2999999999999998,
                            Signed = true,
                            Title = "The Silent Library #20"
                        },
                        new
                        {
                            Id = 21,
                            Author = "M. Castillo",
                            Description = "Short chapters, practical insights, and zero fluff—made for busy readers.",
                            ImagePath = "https://picsum.photos/seed/library_book_21/600/900",
                            Rating = 3.2000000000000002,
                            Signed = false,
                            Title = "Pages of Time #21"
                        },
                        new
                        {
                            Id = 22,
                            Author = "R. Bennett",
                            Description = "A field note from the front desk: what to keep, what to search, and when.",
                            ImagePath = "https://picsum.photos/seed/library_book_22/600/900",
                            Rating = 4.4000000000000004,
                            Signed = false,
                            Title = "Ink & Ideas #22"
                        },
                        new
                        {
                            Id = 23,
                            Author = "L. Nakamura",
                            Description = "Tiny patterns that scale from a single page to a whole system.",
                            ImagePath = "https://picsum.photos/seed/library_book_23/600/900",
                            Rating = 4.0999999999999996,
                            Signed = false,
                            Title = "Beyond The Stacks #23"
                        },
                        new
                        {
                            Id = 24,
                            Author = "H. Ibrahim",
                            Description = "Calm explanations with examples you can try the same day.",
                            ImagePath = "https://picsum.photos/seed/library_book_24/600/900",
                            Rating = 3.6000000000000001,
                            Signed = false,
                            Title = "Patterns of Code #24"
                        },
                        new
                        {
                            Id = 25,
                            Author = "C. Martin",
                            Description = "A concise, human-friendly guide that turns complex ideas into daily tools.",
                            ImagePath = "https://picsum.photos/seed/library_book_25/600/900",
                            Rating = 5.0,
                            Signed = true,
                            Title = "Sands of Memory #25"
                        },
                        new
                        {
                            Id = 26,
                            Author = "S. Patel",
                            Description = "Short chapters, practical insights, and zero fluff—made for busy readers.",
                            ImagePath = "https://picsum.photos/seed/library_book_26/600/900",
                            Rating = 4.2999999999999998,
                            Signed = false,
                            Title = "Hidden Chapters #26"
                        },
                        new
                        {
                            Id = 27,
                            Author = "N. Alvarez",
                            Description = "A field note from the front desk: what to keep, what to search, and when.",
                            ImagePath = "https://picsum.photos/seed/library_book_27/600/900",
                            Rating = 3.6000000000000001,
                            Signed = false,
                            Title = "The Archivist #27"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Y. Chen",
                            Description = "Tiny patterns that scale from a single page to a whole system.",
                            ImagePath = "https://picsum.photos/seed/library_book_28/600/900",
                            Rating = 4.2999999999999998,
                            Signed = true,
                            Title = "Refactor Your Mind #28"
                        },
                        new
                        {
                            Id = 29,
                            Author = "D. Howard",
                            Description = "Calm explanations with examples you can try the same day.",
                            ImagePath = "https://picsum.photos/seed/library_book_29/600/900",
                            Rating = 4.5,
                            Signed = true,
                            Title = "Designing Harmony #29"
                        },
                        new
                        {
                            Id = 30,
                            Author = "A. Reynolds",
                            Description = "A concise, human-friendly guide that turns complex ideas into daily tools.",
                            ImagePath = "https://picsum.photos/seed/library_book_30/600/900",
                            Rating = 4.2000000000000002,
                            Signed = false,
                            Title = "The Silent Library #30"
                        },
                        new
                        {
                            Id = 31,
                            Author = "M. Castillo",
                            Description = "Short chapters, practical insights, and zero fluff—made for busy readers.",
                            ImagePath = "https://picsum.photos/seed/library_book_31/600/900",
                            Rating = 3.5,
                            Signed = true,
                            Title = "Pages of Time #31"
                        },
                        new
                        {
                            Id = 32,
                            Author = "R. Bennett",
                            Description = "A field note from the front desk: what to keep, what to search, and when.",
                            ImagePath = "https://picsum.photos/seed/library_book_32/600/900",
                            Rating = 3.8999999999999999,
                            Signed = true,
                            Title = "Ink & Ideas #32"
                        },
                        new
                        {
                            Id = 33,
                            Author = "L. Nakamura",
                            Description = "Tiny patterns that scale from a single page to a whole system.",
                            ImagePath = "https://picsum.photos/seed/library_book_33/600/900",
                            Rating = 3.3999999999999999,
                            Signed = false,
                            Title = "Beyond The Stacks #33"
                        },
                        new
                        {
                            Id = 34,
                            Author = "H. Ibrahim",
                            Description = "Calm explanations with examples you can try the same day.",
                            ImagePath = "https://picsum.photos/seed/library_book_34/600/900",
                            Rating = 4.5999999999999996,
                            Signed = true,
                            Title = "Patterns of Code #34"
                        },
                        new
                        {
                            Id = 35,
                            Author = "C. Martin",
                            Description = "A concise, human-friendly guide that turns complex ideas into daily tools.",
                            ImagePath = "https://picsum.photos/seed/library_book_35/600/900",
                            Rating = 3.5,
                            Signed = true,
                            Title = "Sands of Memory #35"
                        },
                        new
                        {
                            Id = 36,
                            Author = "S. Patel",
                            Description = "Short chapters, practical insights, and zero fluff—made for busy readers.",
                            ImagePath = "https://picsum.photos/seed/library_book_36/600/900",
                            Rating = 3.5,
                            Signed = true,
                            Title = "Hidden Chapters #36"
                        },
                        new
                        {
                            Id = 37,
                            Author = "N. Alvarez",
                            Description = "A field note from the front desk: what to keep, what to search, and when.",
                            ImagePath = "https://picsum.photos/seed/library_book_37/600/900",
                            Rating = 3.7000000000000002,
                            Signed = true,
                            Title = "The Archivist #37"
                        },
                        new
                        {
                            Id = 38,
                            Author = "Y. Chen",
                            Description = "Tiny patterns that scale from a single page to a whole system.",
                            ImagePath = "https://picsum.photos/seed/library_book_38/600/900",
                            Rating = 3.6000000000000001,
                            Signed = true,
                            Title = "Refactor Your Mind #38"
                        },
                        new
                        {
                            Id = 39,
                            Author = "D. Howard",
                            Description = "Calm explanations with examples you can try the same day.",
                            ImagePath = "https://picsum.photos/seed/library_book_39/600/900",
                            Rating = 4.9000000000000004,
                            Signed = true,
                            Title = "Designing Harmony #39"
                        },
                        new
                        {
                            Id = 40,
                            Author = "A. Reynolds",
                            Description = "A concise, human-friendly guide that turns complex ideas into daily tools.",
                            ImagePath = "https://picsum.photos/seed/library_book_40/600/900",
                            Rating = 4.7999999999999998,
                            Signed = false,
                            Title = "The Silent Library #40"
                        },
                        new
                        {
                            Id = 41,
                            Author = "M. Castillo",
                            Description = "Short chapters, practical insights, and zero fluff—made for busy readers.",
                            ImagePath = "https://picsum.photos/seed/library_book_41/600/900",
                            Rating = 4.4000000000000004,
                            Signed = true,
                            Title = "Pages of Time #41"
                        },
                        new
                        {
                            Id = 42,
                            Author = "R. Bennett",
                            Description = "A field note from the front desk: what to keep, what to search, and when.",
                            ImagePath = "https://picsum.photos/seed/library_book_42/600/900",
                            Rating = 3.7999999999999998,
                            Signed = false,
                            Title = "Ink & Ideas #42"
                        },
                        new
                        {
                            Id = 43,
                            Author = "L. Nakamura",
                            Description = "Tiny patterns that scale from a single page to a whole system.",
                            ImagePath = "https://picsum.photos/seed/library_book_43/600/900",
                            Rating = 3.5,
                            Signed = false,
                            Title = "Beyond The Stacks #43"
                        },
                        new
                        {
                            Id = 44,
                            Author = "H. Ibrahim",
                            Description = "Calm explanations with examples you can try the same day.",
                            ImagePath = "https://picsum.photos/seed/library_book_44/600/900",
                            Rating = 4.0999999999999996,
                            Signed = true,
                            Title = "Patterns of Code #44"
                        },
                        new
                        {
                            Id = 45,
                            Author = "C. Martin",
                            Description = "A concise, human-friendly guide that turns complex ideas into daily tools.",
                            ImagePath = "https://picsum.photos/seed/library_book_45/600/900",
                            Rating = 3.2000000000000002,
                            Signed = true,
                            Title = "Sands of Memory #45"
                        },
                        new
                        {
                            Id = 46,
                            Author = "S. Patel",
                            Description = "Short chapters, practical insights, and zero fluff—made for busy readers.",
                            ImagePath = "https://picsum.photos/seed/library_book_46/600/900",
                            Rating = 4.5,
                            Signed = true,
                            Title = "Hidden Chapters #46"
                        },
                        new
                        {
                            Id = 47,
                            Author = "N. Alvarez",
                            Description = "A field note from the front desk: what to keep, what to search, and when.",
                            ImagePath = "https://picsum.photos/seed/library_book_47/600/900",
                            Rating = 4.5999999999999996,
                            Signed = true,
                            Title = "The Archivist #47"
                        },
                        new
                        {
                            Id = 48,
                            Author = "Y. Chen",
                            Description = "Tiny patterns that scale from a single page to a whole system.",
                            ImagePath = "https://picsum.photos/seed/library_book_48/600/900",
                            Rating = 4.0,
                            Signed = false,
                            Title = "Refactor Your Mind #48"
                        },
                        new
                        {
                            Id = 49,
                            Author = "D. Howard",
                            Description = "Calm explanations with examples you can try the same day.",
                            ImagePath = "https://picsum.photos/seed/library_book_49/600/900",
                            Rating = 4.7000000000000002,
                            Signed = false,
                            Title = "Designing Harmony #49"
                        },
                        new
                        {
                            Id = 50,
                            Author = "A. Reynolds",
                            Description = "A concise, human-friendly guide that turns complex ideas into daily tools.",
                            ImagePath = "https://picsum.photos/seed/library_book_50/600/900",
                            Rating = 3.3999999999999999,
                            Signed = false,
                            Title = "The Silent Library #50"
                        });
                });

            modelBuilder.Entity("library.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Saud",
                            PasswordHash = "5ecf004a27f10e2ec9350207cb1cc45134e9be971a48ca0dd04f309933759075",
                            Username = "saud"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
